= Anas Shakra - Project Portfolio
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Tuition Connect (TC)

---

== Overview

TuitionConnect is a desktop address book application used by private tuition teacher. +

TuitionConnect aims to help the tutors to manage their busy schedule more efficiently and effectively. +

TuitionConnect has many functionality catered to the tutors - adding and deleting a tutee, creating a schedule, rescheduling and many more. +

The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 20 kLoC.

== Summary of contributions

* *Major enhancement*: Integrated *a new Task class into the application*
** What it does: The addressbook application is now able to interact, in various ways, with the newly created task object. In doing so, tutors are capable of generating and manipulating their various appointments at will. This enhancment inclues the ability to store the task object in the addressbook.
** Justification: This feature forms the foundation of the application as the app is based on a tutor's ability to create and interact with a task object in an addressbook environemnt.
** Highlights: This enhancement affects existing commands and commands to be added in future. It required an in-depth analysis of design alternatives. The implementation too was challenging as it required changes to almost every aspect of the codebase.
** Credits: While no outside code was used, it was useful to look over how the Person class interacted with the addressbook and see how that can be adjusted to allow the pre-existing codebase to accomodate the Task object.

* *Minor enhancement*: added a listTask command that allows the user to view all tasks stored in the addressbook.

* *Code contributed*: [https://github.com/CS2103JAN2018-T11-B1/main/blob/master/collated/functional/a-shakra.md[Functional code]] [https://github.com/CS2103JAN2018-T11-B1/main/blob/master/collated/test/a-shakra.md[Test code]]

* *Other contributions*:

** Project management:
*** Managed releases `v1.2` - `v1.4` (3 releases) on GitHub
** Enhancements to existing features:
*** Wrote additional tests for existing features (https://github.com[#68], https://github.com[#140])
** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide: https://github.com[#68]
*** Updated Developer Guide to explain features: https://github.com[#68]
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com[#128]


== Contributions to the User Guide

include::../UserGuide.adoc[tag=listTask]

== Contributions to the Developer Guide

include::../DeveloperGuide.adoc[tag=taskClass]

include::../DeveloperGuide.adoc[tag=listCommand]
